name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DB_USER: ${{ vars.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  DB_HOST: db
  DB_PORT: 3306
  DB_NAME: test
  REDIS_HOST: redis
  REDIS_PORT: 6379

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test-and-lint
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Containers
      run: docker compose build
    - name: Run tests
      run: docker compose run --rm test
    - name: Cleanup
      if: always()
      run: docker compose down -v
